*: use PointerTo instead of PtrTo
  Error: SA1019: reflect.PtrTo has been deprecated since Go 1.22 and an alternative has been available since Go 1.18: Superseded by [PointerTo].  (staticcheck)

These methods are exactly the same.

Signed-off-by: Roman Khimov <roman@nspcc.ru>